Ext.define("MyApp.proxy.SampleData", {
    sampleItemData: [
        {
            "text": "Tomas.Andersen",
            "leaf": true,
            "firstName": "Tomas",
            "lastName": "Andersen",
            "email": "tom@andersen.com",
            "phoneNumber": "+79214344562",
            "id": "MyApp.model.Item-1",
            "parentId": "root",
            "index": 0,
            "depth": 1,
            "expanded": false,
            "expandable": true,
            "checked": null,
            "cls": "",
            "iconCls": "",
            "icon": "",
            "root": false,
            "isLast": false,
            "isFirst": true,
            "allowDrop": true,
            "allowDrag": true,
            "loaded": false,
            "loading": false,
            "href": "",
            "hrefTarget": "",
            "qtip": "",
            "qtitle": "",
            "qshowDelay": 0,
            "children": null,
            "visible": true
        }, {
            "text": "Team.Musicians",
            "leaf": false,
            "children": [{
                "text": "Amadeus.Mozart",
                "leaf": true,
                "firstName": "Amadeus",
                "lastName": "Mozart",
                "email": "amadeus@mozart.com",
                "phoneNumber": "+79112007763",
                "id": "MyApp.model.Item-4",
                "parentId": "MyApp.model.Item-2",
                "index": 0,
                "depth": 2,
                "expanded": false,
                "expandable": true,
                "checked": null,
                "cls": "",
                "iconCls": "",
                "icon": "",
                "root": false,
                "isLast": true,
                "isFirst": true,
                "allowDrop": true,
                "allowDrag": true,
                "loaded": false,
                "loading": false,
                "href": "",
                "hrefTarget": "",
                "qtip": "",
                "qtitle": "",
                "qshowDelay": 0,
                "children": null,
                "visible": true
            }],
            "id": "MyApp.model.Item-2",
            "parentId": "root",
            "index": 1,
            "depth": 1,
            "expanded": false,
            "expandable": true,
            "checked": null,
            "cls": "",
            "iconCls": "",
            "icon": "",
            "root": false,
            "isLast": false,
            "isFirst": false,
            "allowDrop": true,
            "allowDrag": true,
            "loaded": true,
            "loading": false,
            "href": "",
            "hrefTarget": "",
            "qtip": "",
            "qtitle": "",
            "qshowDelay": 0,
            "visible": true,
            "firstName": "",
            "lastName": "",
            "email": "",
            "phoneNumber": ""
        },
        {
            "text": "Footballers",
            "leaf": false,
            "children": [{
                "text": "Iker.Casillas",
                "leaf": true,
                "firstName": "3333334Iker",
                "lastName": "55555Casillas",
                "email": "iker@casillas.com",
                "phoneNumber": "+79112345463",
                "id": "MyApp.model.Item-5",
                "parentId": "MyApp.model.Item-3",
                "index": 0,
                "depth": 2,
                "expanded": false,
                "expandable": true,
                "checked": null,
                "cls": "",
                "iconCls": "",
                "icon": "",
                "root": false,
                "isLast": true,
                "isFirst": true,
                "allowDrop": true,
                "allowDrag": true,
                "loaded": false,
                "loading": false,
                "href": "",
                "hrefTarget": "",
                "qtip": "",
                "qtitle": "",
                "qshowDelay": 0,
                "children": null,
                "visible": true
            }],
            "id": "MyApp.model.Item-3",
            "parentId": "root",
            "index": 2,
            "depth": 1,
            "expanded": true,
            "expandable": true,
            "checked": null,
            "cls": "",
            "iconCls": "",
            "icon": "",
            "root": false,
            "isLast": true,
            "isFirst": false,
            "allowDrop": true,
            "allowDrag": true,
            "loaded": true,
            "loading": false,
            "href": "",
            "hrefTarget": "",
            "qtip": "",
            "qtitle": "",
            "qshowDelay": 0,
            "visible": true,
            "firstName": "",
            "lastName": "",
            "email": "",
            "phoneNumber": ""
        }],
    sampleUserGroupData: [
        {
            groupName: "root",
            users: [
                {
                    firstName: "Tomas",
                    lastName: "Andersen",
                    email: "tom@andersen.com",
                    phoneNumber: "+79214344562"
                }]
        },
        {
            groupName: "Team.Musicians",
            users: [
                {
                    firstName: "Amadeus",
                    lastName: "Mozart",
                    email: "amadeus@mozart.com",
                    phoneNumber: "+79112007763"
                }]
        },
        {
            groupName: "Footballers",
            users: [
                {
                    firstName: "3333334Iker",
                    lastName: "55555Casillas",
                    email: "iker@casillas.com",
                    phoneNumber: "+79112345463"
                }]
        }
    ]/*,
    sampleUsersData: [
        {
            firstName: "Tomas",
            lastName: "Andersen",
            email: "tom@andersen.com",
            phoneNumber: "+79214344562",
            groupName: "root"
        },
        {
            firstName: "Amadeus",
            lastName: "Mozart",
            email: "amadeus@mozart.com",
            phoneNumber: "+79112007763",
            groupName: "Team.Musicians"
        },
        {
            firstName: "3333334Iker",
            lastName: "55555Casillas",
            email: "iker@casillas.com",
            phoneNumber: "+79112345463",
            groupName: "Footballers"
        }
    ]*/
});